---
# tasks file for packages
- name: Install list of packages
  become: true
  apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
  vars:
      packages:
      - postgresql-client

- name: Add users
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
  loop: "{{ users }}"

- name: "Add authorized keys"
  become: true
  ansible.posix.authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', 'files/'+ item + '.pubkey') }}"
  with_items: "{{ users }}"